# Run integration test commands

- hosts: test_orchestrator
  tasks:
    - name: send command to start writing events to file
      shell: "{{ test_orchestrator_python_bin }} {{ test_orchestrator_script_dir }}/send-start-cmd.py {{ integration_test_kafka_bootstrap_servers }} {{ kafka_to_nexus_data_dir }}/{{ integration_test_nexus_file_name }} 1"

- hosts: forwarder
  tasks:
    - name: send command to start forwarding EPICS PVs
      shell: "{{ forwarder_virtualenv_path }}/bin/python "{{ forwarder_script_dir }}/{{ forwarder_script_prefix }}_forwarder_start_cmd.py""

- hosts: pipeline_data_generator
  tasks:
    - name: start efu data generation
      shell: "\
        LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib \
          ./{{ integration_test_efu_generator_bin }} \
          -f {{ integration_test_efu_generator_data_file }} \
          -i {{ integration_test_efu_generator_destination_ip }} \
          -t {{ integration_test_efu_generator_throttle }} \
          {{ integration_test_efu_generator_additional_args }}"
      args:
        chdir: "{{ event_formation_unit_install_dir }}/event-formation-unit/bin"
      async: "{{ integration_test_max_async_timeout }}"
      poll: 0
      register: efu_generator

- hosts: test_orchestrator
  tasks:
    - name: change value of EPICS PV
      shell: "\
        {{ epics_install_dir }}/bin/pvput SIMPLE:VALUE1 1; \
        sleep 1; \
        {{ epics_install_dir }}/bin/pvput SIMPLE:VALUE1 2; \
        sleep 1"
